Models/ErrorViewModel.cs
namespace VuelosCRUD.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Models/Vuelo.cs
using System.ComponentModel.DataAnnotations;

namespace VuelosCRUD.Models
{
  public class Vuelo
  {
    public int Id { get; set; }

    [StringLength(8)]
    [Display(Name = "Vuelo")]
    [Required(ErrorMessage = "El número de vuelo es obligatorio")]
    public string NumeroVuelo { get; set; }

    [Display(Name = "Horario LLegada")]
    [Required(ErrorMessage = "El horario de llegada es obligatorio")]
    public DateTime HorarioLLegada { get; set; }

    [StringLength(255)]
    [Display(Name = "Línea Aerea")]
    [Required(ErrorMessage = "La linea aerea es obligatoria")]
    public string LineaAerea { get; set; }
    public bool Demorado { get; set; }
  }
}

Models/VuelosDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace VuelosCRUD.Models
{
  public class VuelosDbContext : DbContext
  {
    public VuelosDbContext(DbContextOptions<VuelosDbContext> options) : base(options) { }

    public DbSet<Vuelo> Vuelos { get; set; }
  }
}

ViewModels/VuelosViewModel.cs
using VuelosCRUD.Models;

namespace VuelosCRUD.ViewModels
{
  public class VuelosViewModel
  {
    public List<Vuelo> Vuelos { get; set; }
    public string Id { get; set; }
  }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using VuelosCRUD.Models;

namespace VuelosCRUD.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Controllers/VuelosController.cs
using Microsoft.AspNetCore.Mvc;
using VuelosCRUD.Models;
using VuelosCRUD.ViewModels;

namespace VuelosCRUD.Controllers
{
  public class VuelosController : Controller
  {
    private VuelosDbContext _context;

    public VuelosController(VuelosDbContext context)
    {
      _context = context;
    }
    protected override void Dispose(bool disposing)
    {
      _context.Dispose();
    }

    public IActionResult Index()
    {
      var vuelos = _context.Vuelos.ToList();

      var viewModel = new VuelosViewModel { Vuelos = vuelos };

      return View(viewModel);
    }

    public IActionResult Create()
    {
      return View("Form");
    }
    public IActionResult Update()
    {
      var vuelos = _context.Vuelos.ToList();
      var viewModel = new VuelosViewModel { Vuelos = vuelos };
      return View(viewModel);
    }
    public IActionResult UpdateById(Vuelo vuelo)
    {
      var updateVuelo = _context.Vuelos.Single(v => v.Id == vuelo.Id);
      return View("Form", updateVuelo);
    }
    public IActionResult Delete()
    {
      var vuelos = _context.Vuelos.ToList();
      var viewModel = new VuelosViewModel { Vuelos = vuelos };
      return View(viewModel);
    }

    public IActionResult DeleteById(Vuelo vuelo)
    {
      var deleteVuelo = _context.Vuelos.Single(v => v.Id == vuelo.Id);

      _context.Remove(deleteVuelo);
      _context.SaveChanges();

      return RedirectPermanent("/Vuelos");
    }

    [ValidateAntiForgeryToken]
    [HttpPost]
    public IActionResult Save(Vuelo vuelo)
    {

      //Validations
      var errors = ModelState.Values.SelectMany(v => v.Errors).ToList();
      if (!ModelState.IsValid)
      {
        return View("Form", vuelo);
      }

      if (vuelo.Id == 0)
      {
        _context.Vuelos.Add(vuelo);
      }
      else
      {
        _context.Vuelos.Update(vuelo);
      }

      _context.SaveChanges();

      return RedirectToAction(nameof(Index));
    }
  }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VuelosCRUD</title>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.4/bootstrap-icons.svg" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VuelosCRUD.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <partial name="_Navbar.cshtml"/>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - VuelosCRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Navbar.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
  <div class="container-fluid container">
    <a class="navbar-brand" asp-area="" asp-controller="Vuelos" asp-action="Index">VuelosCRUD</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse d-sm-inline-flex justify-content-between">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link text-dark" asp-area="" asp-controller="Vuelos" asp-action="Create">Alta</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" asp-area="" asp-controller="Vuelos" asp-action="Delete">Baja</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" asp-area="" asp-controller="Vuelos" asp-action="Update">Modificación</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

Views/Vuelos/Delete.cshtml
@model VuelosCRUD.ViewModels.VuelosViewModel

@{
  ViewData["Title"] = "Baja";
}

<div>
  <h1>Baja</h1>
  @using (Html.BeginForm("DeleteById", "Vuelos"))
  {
    <div class="form-group">
      @Html.DropDownListFor(m => m.Id, new SelectList(Model.Vuelos, "Id", "NumeroVuelo"))
      @Html.ValidationMessageFor(m => m.Id)
    </div>
    <button class="btn btn-primary">Eliminar</button>
  }
</div>

Views/Vuelos/Form.cshtml
@model VuelosCRUD.Models.Vuelo

@{
  var isNew = Model == null || Model.Id == 0;
  ViewData["Title"] = isNew ? "Alta" : "Modificación";
}

<div>
  <h1>@(isNew ? "Alta" : "Modificación")</h1>
  <form asp-action="Save" method="POST">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
      <label asp-for="HorarioLLegada" class="control-label"></label>
      <input asp-for="HorarioLLegada" class="form-control" placeholder="HH/mm" />
      <span asp-validation-for="HorarioLLegada" class="text-danger"></span>
    </div>
    <div class="form-group">
      <label asp-for="NumeroVuelo" class="control-label"></label>
      <input asp-for="NumeroVuelo" class="form-control" placeholder="ej: AU 2239" />
      <span asp-validation-for="NumeroVuelo" class="text-danger"></span>
    </div>
    <div class="form-group">
      <label asp-for="LineaAerea" class="control-label"></label>
      <input asp-for="LineaAerea" class="form-control" placeholder="Nombre de la línea" />
      <span asp-validation-for="LineaAerea" class="text-danger"></span>
    </div>
    <div class="checkbox-group">
      <input type="checkbox" asp-for="Demorado"/>
      <label asp-for="Demorado"></label>
    </div>
    @if(isNew)
    {
      <input type="hidden" asp-for="Id" value="0"/>
    } 
    else
    {
      <input type="hidden" asp-for="Id"/>
    }
    <button type="submit" class="btn btn-primary">Guardar</button>
  </form>
</div>

Views/Vuelos/Index.cshtml
@model VuelosCRUD.ViewModels.VuelosViewModel

@{
	ViewData["Title"] = "Vuelos";
}

<h1>Próximos Vuelos</h1>

@if(Model.Vuelos.Count() > 0)
{
	<table class="table table-striped" id="table-vuelos">
		<thead>
			<tr>
				<th scope="col">Horario llegada</th>
				<th scope="col">Vuelo</th>
				<th scope="col">Línea Aerea</th>
				<th scope="col">Demorado</th>
			</tr>
		</thead>
		<tbody>
				@foreach(var vuelo in Model.Vuelos)
				{
					<tr>
						<td>@vuelo.HorarioLLegada.ToString("HH:mm")</td>
						<td>@vuelo.NumeroVuelo</td>
						<td>@vuelo.LineaAerea</td>
						<td>@(vuelo.Demorado ? "Si" : "No")</td>
					</tr>
				}
		</tbody>
	</table>
}
else
{
	<p>No hay vuelos</p>
}

@section Scripts {
	<script>
		$(document).ready(() => {
			$('#table-vuelos').DataTable({
				language: {
					"decimal": "",
					"emptyTable" : "No Hay información",
					"info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
					"infoFiltered": "(Filtrado de _Max_ total entradas)",
					"infoPostFix": "",
					"thousands" : ",",
					"lengthMenu" : "Mostrar _MENU_ Entradas",
					"loadingRecords": "Cargando...",
					"processing": "Procesando...",
					"search" : "Buscar",
					"zeroRecords":"Sin resultados encontrados",
					"paginate" : {
						"first": "Primero",
						"last": "Ultimo",
						"next": "Siguiente",
						"previous" : "Anterior"
					}
				}
			})
		})
	</script>
}

Views/Vuelos/Update.cshtml
@model VuelosCRUD.ViewModels.VuelosViewModel

@{
  ViewData["Title"] = "Modificación";

}

<div>
  <h1>Modificar</h1>
  @using (Html.BeginForm("UpdateById", "Vuelos"))
  {
    <div class="form-group">
      @Html.DropDownListFor(m => m.Id, new SelectList(Model.Vuelos, "Id", "NumeroVuelo"))
      @Html.ValidationMessageFor(m => m.Id)
    </div>
    <button class="btn btn-primary">Seleccionar</button>
  }
</div>